import { CheckCircle2, Download, ExternalLink, FileCheck2, ShieldCheck, Smartphone } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import PlatformFrame from "@/components/platform/PlatformFrame";

const APK_URL = "https://github.com/nadjimyahiaoui1992-lab/souf-tour/releases/download/v2.0.4/ouedna-2.0.4-universal.apk";
const RELEASE_URL = "https://github.com/nadjimyahiaoui1992-lab/souf-tour/releases/tag/v2.0.4";

export default function DownloadPage() {
  return <PlatformFrame><section className="platform-download-page"><div className="platform-container"><div className="platform-download-hero"><div><span className="platform-eyebrow"><i />مركز تنزيل Ouedna</span><h1>خذ الوادي<br /><em>معك.</em></h1><p>النسخة الرسمية لتطبيق Ouedna Android. استخدم الموقع للتخطيط، والتطبيق للموقع الحي والملاحة أثناء الرحلة.</p><div className="platform-hero-actions"><a className="platform-button platform-button--amber" href={APK_URL}><Download size={18} /> تنزيل APK 2.0.4</a><a className="platform-button platform-button--outline" href={RELEASE_URL} target="_blank" rel="noreferrer"><ExternalLink size={16} /> صفحة الإصدار</a></div></div><div className="platform-download-card"><Image src="/ouedna/ouedna-apk-qr.png" alt="QR لتحميل تطبيق Ouedna" width={180} height={180} /><strong>امسح من هاتفك</strong><span>Android · 2.0.4</span></div></div><div className="platform-download-release"><div><span>الإصدار الحالي</span><strong>Ouedna 2.0.4</strong><small><ShieldCheck size={14} /> ملف APK رسمي من إصدار المشروع</small></div><a className="platform-button platform-button--amber" href={APK_URL}><Download size={16} /> تحميل مباشر</a></div><div className="platform-install-grid"><article><b>01</b><Smartphone size={21} /><h2>نزّل الملف</h2><p>افتح الرابط من هاتف Android واحفظ ملف APK.</p></article><article><b>02</b><ShieldCheck size={21} /><h2>اسمح بالتثبيت</h2><p>عند طلب Android، فعّل السماح للمتصفح المستخدم فقط.</p></article><article><b>03</b><FileCheck2 size={21} /><h2>تحقق من المصدر</h2><p>استخدم صفحة الإصدار وSHA-256 إذا أردت التحقق الإضافي.</p></article><article><b>04</b><CheckCircle2 size={21} /><h2>ثبّت وابدأ</h2><p>افتح الملف، أكمل التثبيت، ثم ابدأ استكشاف وادي سوف.</p></article></div><div className="platform-download-safety"><ShieldCheck size={22} /><div><strong>ملاحظة أمان</strong><p>لا تثبّت APK إلا من رابط Ouedna الرسمي أو صفحة GitHub الرسمية. لا نطلب كلمات مرور أو بيانات بنكية أثناء التثبيت.</p></div></div><div className="platform-download-faq"><h2>أسئلة سريعة</h2><details><summary>هل يعمل التطبيق خارج Google Play؟</summary><p>نعم، هذه النسخة الرسمية توزع مباشرة من صفحة الإصدار، ويجب اتباع خطوات Android للمصادر الخارجية.</p></details><details><summary>هل يمكنني التخطيط من الكمبيوتر؟</summary><p>نعم. استخدم المعالم والخريطة والمجتمع على Souf360، ثم افتح التطبيق للموقع والملاحة الحية.</p></details><details><summary>كيف أعرف أن الملف رسمي؟</summary><p>قارن رابط التحميل بصفحة الإصدار الرسمية وافحص قيمة SHA-256 المعروضة هناك.</p></details></div></div></section></PlatformFrame>;
}
