// Ouedna Vercel gateway: calm-sands editorial entry point for the complete public platform.
import Image from "next/image";
import Link from "next/link";
import { ArrowUpLeft, Compass, Download, History, MapPinned, MessageCircle, Navigation, ShieldCheck, Smartphone, Users } from "lucide-react";

const APK_URL = "https://github.com/nadjimyahiaoui1992-lab/souf-tour/releases/download/v2.0.4/ouedna-2.0.4-universal.apk";
const RELEASE_URL = "https://github.com/nadjimyahiaoui1992-lab/souf-tour/releases/tag/v2.0.4";

const destinations = [
  { tag: "عمارة سوفية", title: "ملامح القباب البيضاء", text: "أزقة وواجهات تحمل ذاكرة مدينة الألف قبة.", image: "/ouedna/local-architecture.webp", href: "/explore" },
  { tag: "واحة", title: "أسواق وظلال النخيل", text: "تفاصيل يومية وروائح محلية لا تُنسى.", image: "/ouedna/palm-oasis.jpg", href: "/explore" },
  { tag: "رمال", title: "إيقاع الكثبان", text: "طريق هادئ بين الرمل والذاكرة.", image: "/ouedna/dunes.webp", href: "/map" },
];

export default function LandingPage() {
  return <main id="main-content" className="ouedna-site" dir="rtl">
    <header className="ouedna-header"><div className="ouedna-header__inner">
      <Link className="ouedna-brand" href="/" aria-label="Ouedna - الصفحة الرئيسية"><span className="ouedna-brand__mark"><Image src="/ouedna/mark.svg" alt="" width={36} height={36} /></span><span><strong>وادنا</strong><small>Ouedna</small></span></Link>
      <nav className="ouedna-nav" aria-label="التنقل الرئيسي"><Link href="/explore">استكشف</Link><Link href="/map">الخريطة</Link><Link href="/archive">ذاكرة الوادي</Link><Link href="/community">المجتمع</Link></nav>
      <div className="ouedna-header-actions"><Link className="ouedna-header-download" href="/download"><Download size={15} /> تحميل التطبيق</Link><details className="ouedna-mobile-menu"><summary aria-label="فتح القائمة">☰</summary><div><Link href="/explore">استكشف</Link><Link href="/map">الخريطة</Link><Link href="/archive">ذاكرة الوادي</Link><Link href="/community">المجتمع</Link><Link href="/download">تحميل التطبيق</Link></div></details></div>
    </div></header>

    <section className="ouedna-hero"><Image className="ouedna-hero__image" src="/ouedna/hero-oasis.jpg" alt="واحة وكثبان وادي سوف عند الغروب" fill priority sizes="100vw" /><div className="ouedna-hero__veil" /><div className="ouedna-hero__dune" /><div className="ouedna-hero__content ouedna-width">
      <div className="ouedna-hero__copy"><p className="ouedna-eyebrow ouedna-eyebrow--light"><span /> الدليل الرقمي لولاية الوادي</p><h1>اكتشف الوادي<br /><em>على إيقاعك.</em></h1><p className="ouedna-hero__lede">استكشف المعالم، خطّط طريقك، واحفظ حكايات المكان في منصة واحدة على الكمبيوتر، ثم خذ الملاحة الحية معك عبر تطبيق Ouedna.</p><div className="ouedna-hero__actions"><Link className="ouedna-button ouedna-button--amber" href="/explore"><Compass size={18} /> ابدأ الاستكشاف</Link><Link className="ouedna-light-link" href="/map">افتح الخريطة <MapPinned size={16} /></Link></div><div className="ouedna-hero__meta"><span><ShieldCheck size={14} /> بيانات المعالم من Supabase</span><i /><span>عربي · Français · English</span></div><div className="ouedna-download-trust"><Image src="/ouedna/ouedna-apk-qr.png" alt="رمز QR لتحميل تطبيق Ouedna" width={74} height={74} /><div><strong>امسح وحمّل Ouedna <Download size={13} /></strong><span>Android · الإصدار 2.0.4</span><small><ShieldCheck size={12} /> تنزيل رسمي خارج Google Play</small></div></div></div>
      <div className="ouedna-route-card"><div className="ouedna-route-card__label"><Navigation size={15} /> اتجاهك يبدأ من هنا</div><div className="ouedna-route-card__window"><div className="ouedna-map-lines" /><div className="ouedna-map-pin ouedna-map-pin--one"><span>واحة</span></div><div className="ouedna-map-pin ouedna-map-pin--two"><span>متحف</span></div><div className="ouedna-map-route" /></div><div className="ouedna-route-card__footer"><div><small>وجهتك التالية</small><strong>واحة النخيل</strong></div><span><Navigation size={14} /> 12 د</span></div></div>
    </div></section>

    <section className="ouedna-intro" id="discover"><div className="ouedna-width ouedna-intro__grid"><div className="ouedna-kicker">Ouedna / 01<i /></div><div><p className="ouedna-eyebrow">منصة واحدة لرحلة كاملة</p><h2>كل ما تحتاجه<br /><span>قبل أن تصل.</span></h2></div><div className="ouedna-intro__copy"><p>الشاشة الكبيرة تمنحك الصورة الكاملة: معالم حقيقية، خريطة قابلة للتخطيط، أرشيف حي، وتجارب أهل الوادي. التطبيق يرافقك بعد ذلك في الطريق.</p><Link className="ouedna-text-link" href="/explore">اكتشف المنصة <ArrowUpLeft size={16} /></Link></div></div></section>
    <div className="ouedna-dune-divider ouedna-width"><span>وادي سوف</span><i /></div>
    <section className="ouedna-highlights"><div className="ouedna-width ouedna-highlights__grid"><article><b>01</b><span><Compass size={20} /></span><h3>استكشف المعالم</h3><p>صور حقيقية وتصنيفات ومعلومات من قاعدة البيانات الحية.</p><Link className="ouedna-text-link" href="/explore">اذهب إلى المعالم <ArrowUpLeft size={14} /></Link></article><article><b>02</b><span><Navigation size={20} /></span><h3>خطّط مسارك</h3><p>خريطة واسعة، دبابيس مصورة، وتحديد موقع ومسارات مباشرة.</p><Link className="ouedna-text-link" href="/map">افتح الخريطة <ArrowUpLeft size={14} /></Link></article><article><b>03</b><span><Users size={20} /></span><h3>صوت الزوار</h3><p>تجارب وأسئلة واقتراحات تُراجع قبل أن تظهر للمجتمع.</p><Link className="ouedna-text-link" href="/community">ادخل المجتمع <ArrowUpLeft size={14} /></Link></article></div></section>

    <section className="ouedna-places" id="places"><div className="ouedna-width"><div className="ouedna-section-heading"><div><p className="ouedna-eyebrow">من الخريطة إلى الذاكرة</p><h2>النخيل، القباب،<br /><span>وذاكرة الرمل.</span></h2></div><p>ابدأ من مشهد محلي، ثم افتح دليل المعالم الحي لتجد التفاصيل والإحداثيات والصور المنشورة.</p></div><div className="ouedna-places__grid">{destinations.map((place, index) => <Link className={`ouedna-place ouedna-place--${index + 1}`} key={place.title} href={place.href}><div className="ouedna-place__image"><Image src={place.image} alt={place.title} fill sizes="(max-width: 680px) 50vw, 33vw" /><span>{place.tag}</span><small>وادنا / 0{index + 1}</small></div><div className="ouedna-place__body"><h3>{place.title}</h3><p>{place.text}</p><b><ArrowUpLeft size={16} /></b></div></Link>)}</div></div></section>
    <section className="ouedna-journey"><Image src="/ouedna/dunes.webp" alt="كثبان وادي سوف" fill sizes="100vw" /><div className="ouedna-journey__veil" /><div className="ouedna-width ouedna-journey__content"><p>رحلتك، بطريقتك</p><h2>خطّط بهدوء،<br /><em>وتحرّك بثقة.</em></h2><span>افتح الخريطة من الكمبيوتر، احفظ ما يهمك، ثم استخدم تطبيق Ouedna للموقع الحي والمسارات وحساب الوقت.</span><Link className="ouedna-button ouedna-button--outline" href="/download"><Smartphone size={17} /> حمّل التطبيق</Link></div><div className="ouedna-journey__index">02 <i /> الخريطة الحيّة</div></section>
    <section className="ouedna-community" id="community"><div className="ouedna-width ouedna-community__grid"><div><p className="ouedna-eyebrow">ذاكرة ومجتمع / 03</p><h2>المكان يكبر<br /><span>بأهله.</span></h2><p>شارك تجربة أو صورة أو اقتراحاً. تُراجع المشاركات قبل نشرها، لتبقى المنصة مرآة صادقة لوادي سوف.</p><Link className="ouedna-text-link" href="/community">شارك في الحكاية <MessageCircle size={16} /></Link></div><div className="ouedna-notes"><Link href="/archive"><History size={22} /><div><strong>ذاكرة الوادي</strong><p>صور قديمة وحكايات تحفظ روح سوف.</p></div><b>01</b></Link><Link href="/community"><MessageCircle size={22} /><div><strong>تجارب الزوار</strong><p>آراء وصور تصل إلى الفريق للمراجعة.</p></div><b>02</b></Link><Link href="/community"><Users size={22} /><div><strong>اقتراحات وأسئلة</strong><p>نكتشف معاً ونُحسن الدليل كل يوم.</p></div><b>03</b></Link></div></div></section>
    <section className="ouedna-install" id="install"><div className="ouedna-width ouedna-install__grid"><div><p className="ouedna-eyebrow">جاهز للانطلاق؟ / 04</p><h2>خذ وادنا<br /><span>معك.</span></h2><p>التطبيق مجاني وخفيف ومصمم لمرافقتك خارج المتجر. نزّل النسخة الرسمية، وتحقق من الإصدار، ثم ابدأ.</p><Link className="ouedna-button ouedna-button--green" href="/download"><Download size={18} /> تحميل Ouedna 2.0.4</Link><Link className="ouedna-release-link" href={RELEASE_URL}>عرض الإصدار وSHA-256 <ArrowUpLeft size={15} /></Link></div><div className="ouedna-install__steps"><article><b>01</b><div><strong>نزّل الملف</strong><p>افتح صفحة التنزيل من هاتف Android.</p></div><ShieldCheck size={17} /></article><article><b>02</b><div><strong>اسمح بالتثبيت</strong><p>اتبع إرشادات Android للمصادر الخارجية.</p></div><Download size={17} /></article><article><b>03</b><div><strong>افتح وابدأ</strong><p>استخدم الخريطة والملاحة كما تريد.</p></div><Navigation size={17} /></article></div></div></section>
    <footer className="ouedna-footer"><div className="ouedna-width ouedna-footer__top"><Link className="ouedna-brand" href="/"><span className="ouedna-brand__mark"><Image src="/ouedna/mark.svg" alt="" width={36} height={36} /></span><span><strong>وادنا</strong><small>Ouedna</small></span></Link><p>بوابة اكتشاف وادي سوف، من الموقع إلى الطريق.</p><nav><Link href="/explore">المعالم</Link><Link href="/map">الخريطة</Link><Link href="/archive">الأرشيف</Link><Link href="/privacy">الخصوصية</Link></nav></div><div className="ouedna-width ouedna-footer__bottom"><span>© 2026 Ouedna · وادنا</span><span>صنع من أجل الوادي</span></div></footer>
  </main>;
}
