"use client";

import { Compass, Heart, MapPin, Search, Star } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Place = { id: string | number; name?: string; category?: string; description?: string; image_url?: unknown; municipality?: string; lat?: number; lng?: number; rating?: number };

function imageFor(value: unknown) { if (Array.isArray(value)) return String(value[0] || ""); if (typeof value === "string") return value.replace(/[\[\]"']/g, "").split(",")[0]?.trim() || ""; return ""; }

export default function AppExploreClient({ places }: { places: Place[] }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("الكل"); const [favorites, setFavorites] = useState<string[]>([]);
  useEffect(() => setFavorites(JSON.parse(localStorage.getItem("souf360_favorites") || "[]").map(String)), []);
  const categories = useMemo(() => ["الكل", ...Array.from(new Set(places.map((place) => place.category).filter(Boolean) as string[]))], [places]);
  const filtered = useMemo(() => places.filter((place) => { const haystack = `${place.name || ""} ${place.description || ""} ${place.category || ""} ${place.municipality || ""}`.toLowerCase(); return (category === "الكل" || place.category === category) && (!query.trim() || haystack.includes(query.toLowerCase().trim())); }), [places, query, category]);
  function toggleFavorite(id: string | number) { const current = new Set(favorites); const key = String(id); current.has(key) ? current.delete(key) : current.add(key); const next = [...current]; localStorage.setItem("souf360_favorites", JSON.stringify(next)); setFavorites(next); }
  return <section className="app-explore-page platform-page"><div className="platform-container"><div className="app-screen-heading"><div><span className="platform-eyebrow"><i />02 / دليل المعالم</span><h1>استكشف<br /><em>الأماكن.</em></h1><p>ابحث، صفِّ، واحفظ الأماكن التي تريد أن تراها في رحلتك.</p></div><div className="app-screen-heading__icon"><Compass size={28} /></div></div><div className="app-explore-toolbar"><label><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث عن معلم، سوق، واحة..." /></label><div className="app-category-scroll">{categories.map((item) => <button key={item} type="button" className={category === item ? "is-active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="app-results-meta"><span>{filtered.length} معلم متاح</span><span>البيانات المعتمدة من Ouedna</span></div>{filtered.length ? <div className="app-explore-grid">{filtered.map((place) => { const image = imageFor(place.image_url) || "/ouedna/local-architecture.webp"; const saved = favorites.includes(String(place.id)); return <article className="app-explore-card" key={place.id}><Link href={`/place/${place.id}`} className="app-explore-card__image"><img src={image} alt={place.name || "معلم من وادي سوف"} onError={(event) => { event.currentTarget.src = "/ouedna/local-architecture.webp"; }} /><span>{place.category || "معلم سياحي"}</span></Link><button className={`app-explore-card__favorite${saved ? " is-active" : ""}`} type="button" aria-label={saved ? "إزالة من المفضلة" : "إضافة إلى المفضلة"} onClick={() => toggleFavorite(place.id)}><Heart size={17} fill={saved ? "currentColor" : "none"} /></button><div className="app-explore-card__body"><Link href={`/place/${place.id}`}><h2>{place.name || "معلم من وادي سوف"}</h2></Link><p><MapPin size={14} />{place.municipality || "ولاية الوادي"}</p><div><span><Star size={13} fill="currentColor" /> {place.rating ? Number(place.rating).toFixed(1) : "جديد"}</span><Link href={`/map?placeId=${place.id}&destination=${encodeURIComponent(place.name || "")}`}>إلى الخريطة ←</Link></div></div></article>; })}</div> : <div className="platform-empty-panel"><Search size={28} /><h2>لا توجد نتائج مطابقة</h2><p>جرّب كلمة أخرى أو أعد اختيار كل التصنيفات.</p><button className="platform-button platform-button--green" type="button" onClick={() => { setQuery(""); setCategory("الكل"); }}>إعادة التصفية</button></div>}<div className="app-explore-suggest"><div><strong>تعرف معلماً غير موجود؟</strong><p>أضفه إلى الدليل وسيظهر بعد مراجعة الإدارة.</p></div><Link className="platform-button platform-button--amber" href="/suggest-place">اقتراح معلم</Link></div></div></section>;
}
