"use client";

import { Camera, CheckCircle2, LoaderCircle, MapPin, Send } from "lucide-react";
import { useRef, useState } from "react";
import { SUPABASE_ANON_KEY, SUPABASE_URL } from "@/lib/supabase/config";

function toBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] || ""); reader.onerror = () => reject(new Error("تعذر قراءة الصورة")); reader.readAsDataURL(file); }); }

export default function SuggestPlaceClient() {
  const fileRef = useRef<HTMLInputElement>(null); const [sending, setSending] = useState(false); const [success, setSuccess] = useState(false); const [notice, setNotice] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const file = fileRef.current?.files?.[0]; if (file && file.size > 8 * 1024 * 1024) { setNotice("حجم الصورة يجب ألا يتجاوز 8 ميغابايت."); return; } setSending(true); setNotice(""); setSuccess(false); try { const image = file ? await toBase64(file) : null; const response = await fetch(`${SUPABASE_URL}/functions/v1/submit-visitor-place`, { method: "POST", headers: { apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify({ name: String(form.get("name") || "").trim(), main_category: String(form.get("main_category") || "").trim(), sub_category: String(form.get("sub_category") || "").trim() || null, description: String(form.get("description") || "").trim() || null, address: String(form.get("address") || "").trim() || null, municipality: String(form.get("municipality") || "").trim() || null, phone: String(form.get("phone") || "").trim() || null, latitude: Number(form.get("latitude")) || null, longitude: Number(form.get("longitude")) || null, image_base64: image, image_file_name: file?.name || null }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || body.error || "تعذر إرسال الاقتراح"); event.currentTarget.reset(); setSuccess(true); setNotice("تم استلام المعلم وسيظهر بعد مراجعته وقبوله من الإدارة."); } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر إرسال الاقتراح حالياً."); } finally { setSending(false); } }
  return <form className="platform-suggest-form" onSubmit={submit}><div className="platform-form-section-heading"><span>01</span><div><h2>تعريف المكان</h2><p>الاسم والتصنيف والموقع الأساسي.</p></div></div><div className="platform-form-grid"><label>اسم المعلم *<input name="name" required minLength={2} placeholder="مثال: واحة أو سوق أو قصر" /></label><label>التصنيف الرئيسي *<input name="main_category" required placeholder="معلم تراثي، سوق، طبيعة..." /></label><label>التصنيف الفرعي<input name="sub_category" placeholder="اختياري" /></label><label>البلدية<input name="municipality" placeholder="بلدية الوادي" /></label><label>العنوان<input name="address" placeholder="الحي أو الشارع" /></label><label>الهاتف<input name="phone" type="tel" placeholder="اختياري" /></label></div><div className="platform-form-section-heading"><span>02</span><div><h2>المعلومات المفيدة</h2><p>أضف وصفاً يساعد الزائر على فهم المكان.</p></div></div><label className="platform-form-wide">الوصف<textarea name="description" rows={5} placeholder="ما الذي يميز المكان؟ وما قصته؟" /></label><div className="platform-form-grid"><label>خط العرض<input name="latitude" type="number" step="any" placeholder="33.36" /></label><label>خط الطول<input name="longitude" type="number" step="any" placeholder="6.86" /></label></div><div className="platform-form-section-heading"><span>03</span><div><h2>صورة المكان</h2><p>صورة واضحة اختيارية لبداية المراجعة.</p></div></div><label className="platform-suggest-upload"><Camera size={22} /><span><strong>اختر صورة JPG أو PNG أو WebP</strong><small>حتى 8 ميغابايت · اختيارية</small></span><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" /></label>{notice && <p className={`platform-form-notice${success ? " is-success" : ""}`}>{success && <CheckCircle2 size={16} />}{notice}</p>}<button type="submit" className="platform-button platform-button--amber" disabled={sending}>{sending ? <LoaderCircle className="platform-spin" size={17} /> : <Send size={17} />}{sending ? "جارٍ إرسال الاقتراح..." : "إرسال للمراجعة"}</button></form>;
}
