"use client";

import { Loader2, Mic, Send, Sparkles, UserRound } from "lucide-react";
import { useState } from "react";
import { createClient } from "@supabase/supabase-js";
import { SUPABASE_ANON_KEY, SUPABASE_URL } from "@/lib/supabase/config";

type Message = { role: "assistant" | "user"; text: string; error?: boolean };
const starter = "مرحباً، أنا مساعدك السياحي في وادنا. اسألني عن معلم، برنامج زيارة، ثقافة سوف أو نصيحة عملية لرحلتك.";

export default function GuideClient() {
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", text: starter }]); const [question, setQuestion] = useState(""); const [sending, setSending] = useState(false); const [listening, setListening] = useState(false);
  const prompts = ["ماذا تقترح لزيارة نصف يوم؟", "ما أبرز المعالم التراثية؟", "ما نصائح الزيارة اليوم؟"];
  async function ask(value = question) { const clean = value.trim(); if (!clean || sending) return; setMessages((current) => [...current, { role: "user", text: clean }]); setQuestion(""); setSending(true); try { const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY); const { data, error } = await supabase.functions.invoke("tour-guide-ai", { body: { question: clean } }); if (error) throw error; const answer = data?.answer || data?.response || "أهلاً بك في وادنا! اسألني عن المعالم أو المسار أو ثقافة ولاية الوادي."; setMessages((current) => [...current, { role: "assistant", text: String(answer) }]); } catch { setMessages((current) => [...current, { role: "assistant", text: "يتعذر الاتصال بالمساعد السياحي الآن. تحقق من اتصال الإنترنت ثم أعد المحاولة.", error: true }]); } finally { setSending(false); } }
  function voice() { const SpeechRecognition = (window as unknown as { SpeechRecognition?: new () => { lang: string; start: () => void; onresult: ((event: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null; onend: (() => void) | null } }).SpeechRecognition; if (!SpeechRecognition) { setMessages((current) => [...current, { role: "assistant", text: "الإملاء الصوتي غير متاح في هذا المتصفح. يمكنك كتابة سؤالك مباشرة." }]); return; } const recognition = new SpeechRecognition(); recognition.lang = "ar-DZ"; recognition.onresult = (event) => setQuestion(event.results[0][0].transcript); recognition.onend = () => setListening(false); setListening(true); recognition.start(); }
  return <section className="guide-page platform-page"><div className="platform-container"><div className="app-screen-heading"><div><span className="platform-eyebrow"><i />05 / رفيق الرحلة</span><h1>اسأل<br /><em>وادنا.</em></h1><p>مساعد سياحي يعرف معالم وثقافة ونصائح ولاية الوادي.</p></div><div className="app-screen-heading__icon"><Sparkles size={28} /></div></div><div className="guide-layout"><aside className="guide-aside"><div className="guide-aside__icon"><Sparkles size={23} /></div><h2>مرشدك المحلي</h2><p>اكتب سؤالك بالعربية أو الفرنسية أو الإنجليزية. سيجيبك المساعد عبر نفس خدمة التطبيق.</p><div className="guide-prompts">{prompts.map((prompt) => <button type="button" key={prompt} onClick={() => ask(prompt)}>{prompt}</button>)}</div></aside><div className="guide-chat"><div className="guide-messages">{messages.map((message, index) => <div className={`guide-message guide-message--${message.role}${message.error ? " is-error" : ""}`} key={`${message.role}-${index}`}><span className="guide-message__avatar">{message.role === "assistant" ? <Sparkles size={14} /> : <UserRound size={14} />}</span><p>{message.text}</p></div>)}{sending && <div className="guide-message guide-message--assistant"><span className="guide-message__avatar"><Sparkles size={14} /></span><p><Loader2 size={16} className="animate-spin" /> جاري التفكير...</p></div>}</div><form className="guide-composer" onSubmit={(event) => { event.preventDefault(); ask(); }}><input value={question} onChange={(event) => setQuestion(event.target.value)} disabled={sending} placeholder="اسأل عن مكان، تجربة أو برنامج زيارة…" /><button type="button" className={listening ? "is-listening" : ""} onClick={voice} aria-label="الإملاء الصوتي"><Mic size={17} /></button><button type="submit" disabled={sending || !question.trim()} aria-label="إرسال السؤال"><Send size={17} /></button></form></div></div></div></section>;
}
